// styles.js
export const styles = {
    app: {
        minHeight: '100vh',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        background: 'linear-gradient(135deg, #050811 0%, #0f1129 50%, #0a0e27 100%)',
        fontFamily: "'Rajdhani', -apple-system, BlinkMacSystemFont, sans-serif",
        color: '#ffffff',
        padding: '20px',
    },
    authContainer: {
        width: '100%',
        maxWidth: '450px',
    },
    authCard: {
        background: 'rgba(15, 20, 40, 0.95)',
        borderRadius: '20px',
        padding: '3rem 2.5rem',
        boxShadow: '0 0 60px rgba(0, 255, 255, 0.2), inset 0 0 40px rgba(0, 0, 0, 0.3)',
        border: '2px solid rgba(0, 255, 255, 0.3)',
        backdropFilter: 'blur(10px)',
    },
    cardHeader: {
        textAlign: 'center',
        marginBottom: '2.5rem',
    },
    title: {
        fontFamily: "'Orbitron', monospace",
        fontSize: '2.5rem',
        fontWeight: '900',
        background: 'linear-gradient(135deg, #00ffff, #9d00ff)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        letterSpacing: '3px',
        marginBottom: '0.5rem',
        textShadow: '0 0 30px rgba(0, 255, 255, 0.5)',
    },
    subtitle: {
        fontSize: '1rem',
        color: '#a0a8d4',
        fontWeight: '300',
        letterSpacing: '2px',
        textTransform: 'uppercase',
    },
    inputGroup: {
        marginBottom: '1.5rem',
    },
    label: {
        display: 'block',
        marginBottom: '0.5rem',
        fontSize: '0.9rem',
        color: '#00ffff',
        fontWeight: '600',
        letterSpacing: '1px',
        textTransform: 'uppercase',
        fontFamily: "'Orbitron', monospace",
    },
    input: {
        width: '100%',
        padding: '1rem 1.25rem',
        background: 'rgba(20, 25, 50, 0.6)',
        border: '2px solid rgba(0, 255, 255, 0.2)',
        borderRadius: '12px',
        color: '#ffffff',
        fontSize: '1rem',
        fontFamily: "'Rajdhani', sans-serif",
        outline: 'none',
        transition: 'all 0.3s ease',
    },
    message: {
        padding: '1rem',
        borderRadius: '10px',
        marginBottom: '1.5rem',
        fontWeight: '600',
        textAlign: 'center',
        letterSpacing: '1px',
    },
    error: {
        background: 'rgba(255, 51, 102, 0.1)',
        border: '2px solid #ff3366',
        color: '#ff3366',
    },
    success: {
        background: 'rgba(0, 255, 136, 0.1)',
        border: '2px solid #00ff88',
        color: '#00ff88',
    },
    submitBtn: {
        width: '100%',
        padding: '1.25rem',
        background: 'linear-gradient(135deg, #00ffff, #9d00ff)',
        border: 'none',
        borderRadius: '12px',
        color: '#050811',
        fontSize: '1.1rem',
        fontWeight: '900',
        fontFamily: "'Orbitron', monospace",
        letterSpacing: '3px',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
    },
    toggleMode: {
        textAlign: 'center',
        marginTop: '1.5rem',
        color: '#a0a8d4',
        fontSize: '0.95rem',
    },
    toggleLink: {
        color: '#00ffff',
        fontWeight: '700',
        cursor: 'pointer',
        textDecoration: 'none',
    },
    dashboardContainer: {
        width: '100%',
        maxWidth: '700px',
    },
    dashboardCard: {
        background: 'rgba(15, 20, 40, 0.95)',
        borderRadius: '20px',
        padding: '3rem',
        boxShadow: '0 0 60px rgba(0, 255, 255, 0.2)',
        border: '2px solid rgba(0, 255, 255, 0.3)',
        backdropFilter: 'blur(10px)',
    },
    welcomeSection: {
        marginBottom: '2rem',
    },
    welcomeTitle: {
        fontFamily: "'Orbitron', monospace",
        fontSize: '3rem',
        fontWeight: '900',
        background: 'linear-gradient(135deg, #00ffff, #ff00ff)',
        WebkitBackgroundClip: 'text',
        WebkitTextFillColor: 'transparent',
        marginBottom: '1.5rem',
        letterSpacing: '4px',
    },
    userInfo: {
        background: 'rgba(20, 25, 50, 0.6)',
        borderRadius: '15px',
        padding: '1.5rem',
        border: '2px solid rgba(0, 255, 255, 0.2)',
    },
    infoItem: {
        display: 'flex',
        justifyContent: 'space-between',
        padding: '0.75rem 0',
        borderBottom: '1px solid rgba(0, 255, 255, 0.1)',
    },
    infoLabel: {
        color: '#00ffff',
        fontWeight: '600',
        fontFamily: "'Orbitron', monospace",
        fontSize: '0.9rem',
        letterSpacing: '1px',
    },
    infoValue: {
        color: '#ffffff',
        fontWeight: '600',
        fontSize: '1.1rem',
    },
    logoutBtn: {
        width: '100%',
        padding: '1rem',
        background: 'linear-gradient(135deg, #ff3366, #ff6b88)',
        border: 'none',
        borderRadius: '12px',
        color: 'white',
        fontSize: '1rem',
        fontWeight: '900',
        fontFamily: "'Orbitron', monospace",
        letterSpacing: '3px',
        cursor: 'pointer',
        transition: 'all 0.3s ease',
        marginBottom: '2rem',
    },
    usersSection: {
        marginTop: '2rem',
        paddingTop: '2rem',
        borderTop: '2px solid rgba(0, 255, 255, 0.2)',
    },
    usersSectionTitle: {
        fontFamily: "'Orbitron', monospace",
        color: '#00ffff',
        marginBottom: '1rem',
        fontSize: '1.5rem',
        letterSpacing: '2px',
    },
    usersList: {
        display: 'grid',
        gap: '1rem',
    },
    userCard: {
        background: 'rgba(20, 25, 50, 0.6)',
        padding: '1rem 1.5rem',
        borderRadius: '10px',
        border: '1px solid rgba(0, 255, 255, 0.2)',
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
    },
    userName: {
        fontWeight: '700',
        fontSize: '1.1rem',
        color: '#ffffff',
    },
    userDate: {
        color: '#a0a8d4',
        fontSize: '0.9rem',
    },
};